### ISSUE TITLE
Develop branch release timing

### ISSUE THREAD

**Issue by joshbruce** [phpDocumentor/Reflection#108]
I do apologize if this should be obvious. When is the code in `develop` scheduled to become the next release?

If you know.

I'm working on an extension to display my own projects and how found myself writing something similar to what is already in `develop`. So, I'm curious what's stopping it from becoming the next release? (Would prefer to use an official release than to change my `composer` setup, you know?)

**Comment by jaapio** [comment]
We are currently not satisfied with the ability to extend the objects with extra metadata like requested in #90. I was working on a new api to solve this issue but it didn't work out as expected.

So no new release is scheduled until we found a solution for that.

**Comment by joshbruce** [comment]
@jaapio: Thank you for the reply. I appreciate where you're coming from with the blocker.

Personally, I'm okay with not being able to extend the Reflection classes directly, which seemed to be the problem/question mentioned in #90. The extension I'm working on is more about allowing for multiple projects and printing various components of an API site.

The project does some file traversing of directories to isolate single versions of one or more projects - at which point I would hand everything off to Reflection to create the object model graph: https://github.com/8fold/documenter-php/tree/phpdocumentor-update-reflection

Thank you again, for letting me know the status.

Further, I have decided to to go ahead and use `dev-develop` and have run into a different issue: phpDocumentor/ReflectionDocBlock#106

**Comment by jaapio** [comment]
It took a while but we just tagged v4. 
we decided to delay the support for customizations.
