### ISSUE TITLE
FileReflector fail to parse single use statement

### ISSUE THREAD

**Issue by pahanini** [phpDocumentor/Reflection#125]
Parsed code example (test.php):
```
use common/models{
     Class1, Class2
}; 
```

Error:  `Syntax error, unexpected '{', expecting T_STRING on line 4`

Parser:
```php
$reflector = new FileReflector('test.php', true);
$reflector->process();
```

**Comment by jaapio** [comment]
You might need to update your package since you are using an outdated version of our package. The current development version is the adviced version to start using. But that will have a large impact on your package since that is a complete rewrite.
