### ISSUE TITLE
Extracting WordPress hooks from source

### ISSUE THREAD

**Issue by jcomack** [phpDocumentor/Reflection#143]
Hey there,

I'm attempting to use this package to parse through a WordPress plugin, but I'm running into an issue where I can't seem to expand the possible nodes that get extracted.

So far, I've attempted the following:

Created a `ProjectFactory` and copy-pasted the default strategies, but replaced the `NodesFactory` with a custom one so I could add another visitor. In this visitor, I'm able to extract the extra nodes I want (i.e. WordPress hooks / filters), however this information seems to be lost as soon as I dump the data in the factory, meaning I can't access it as a separate piece of information.

To me, this feels like information gets filtered out further down the chain or something? Am I correct in my assumption? And is there any way to ensure these extra nodes that I extracted will be retained in the final result?

**Comment by mvriel** [comment]
Hey Jimmy, good seeing you here :)

I am having a hard time translating your description to my view on how the code functions. Do you have a small reproduction case that I can toy with and see if I can understand your issue?

**Comment by jaapio** [comment]
I think your issue is releated to #90 and #108.

**Comment by jcomack** [comment]
@mvriel Thanks! 

Well, lets say for example I have a class method along the lines of this:

```php
Class Foo {
    public function bar() {
        // Allow users to call this filter to override the default value.
       return apply_filters( 'my_custom_filter', 'The default value' );
    }
}
```

What I want to do is extract the function `apply_filters`, mark it as a `HookNode` of sorts and be able to set it as a property (or something similar) on the class, so I can later reference it later. The problem is that despite being able to create these `HookNode`s, I can't access them later on, as they seem to have disappeared / been filtered out somewhere down the chain. 

Note that my example could also apply to normal function calls and not just class methods, if that makes any difference.

@jaapio I already browsed those two threads, but seeing as they're quite dated, I wasn't sure if perhaps something had changed in the meanwhile. I might also be misinterpreting some of the information provided there + might not understand the steps I _could_ take. I hope my example helps clarify my issue a bit better.

**Comment by jaapio** [comment]
If I understand your issue clearly you are trying to extend the output of the `ProjectFactory` with extra metadata? 

This library is skipping the internals of a method by default so anything in the method body is omitted. So on what level do you add the `HookNode`?

The output of the factories is very closed at the moment. So it would be hard to add anything else than just the normal php elements. Or you would have to add some data to the docblock which would allow custom tags? 
Maybe you can provide some more information about what you exactly added to the new visitor?

**Comment by jcomack** [comment]
@jaapio Correct! Out of curiosity, why are the internals being skipped?

I made a gist containing the visitor I've written: https://gist.github.com/jcomack/cfc9d172779c6059a567368ff8c76c39

I suppose this data is also available in the docblock property, which I suppose I could traverse through separately, but I'd rather not 😬

**Comment by jaapio** [comment]
We are skipping the internals because we do not care about what is inside the method. From a phpdocumentor perspective the docblocks and function header are important. The other parts are just slowing down the iteration of the parsing. 

maybe we should discuss this in some slack channel? Because I got the feeling that some slow chat is comming up to help you find a solution :-)

**Comment by jcomack** [comment]
Slack sounds fine to me! Which one tho? :P

**Comment by jaapio** [comment]
phpnl?

**Comment by jcomack** [comment]
Sure thing :)

**Comment by jaapio** [comment]
A small recap from what we talked about on slack for future reference. The internals of a method are not processed  by default. But processing the internals of a method could be possible with a custom strategy on the `ProjectFactory` 

```
<?php
use phpDocumentor\Reflection\Php\Factory\AbstractFactory;
use phpDocumentor\Reflection\Php\StrategyContainer;
class WordpressHookStrategt extends AbstractFactory {
    private $strategy
    public function __construct(\phpDocumentor\Reflection\Php\Factory\Method $methodStratery)
    {
        $this->strategy = $methodStratery;
    }
    protected function doCreate($object, StrategyContainer $strategies, ?Context $context = null)
    {
       /** $object is the full phpparser node tree, containg all contents of a mehod */
        $method = $this->strategy->create($object, $strategies, $context);
        $extra_tags = [new \phpDocumentor\Reflection\DocBlock\Tags\Generic('SomeTag')];
        $docblock = new phpDocumentor\Reflection\DocBlock\Description(
            $method->getDescription()->render(),
            $method->getTags() + $extra_tags
        );
        return new \phpDocumentor\Reflection\Php\Method(
            $method->getFqsen(),
            $method->getVisibility()
            /**  ect. */
        );
    }
}
```

because the model of the libraries used in this project is immutable we need to create a new instance. that allows us to extend the method docblock with some extra information.

If it really works like this we might have a way to extend the information processed by this library. Which could be an interesting use case for phpdocumentor itself.
