### ISSUE TITLE
Define in function or method failed to parse

### ISSUE THREAD

**Issue by marcimat** [phpDocumentor/Reflection#233]
Hi, seems somewhere between requirement`^5.0` and `^5.0@dev` (used in phpDocumentor) (now with commit 7666c4bc) a define declaration into function or method failed to parse.

It seems that cdda55ca introduce this problem, as I don’t get it with the previous 07ce695ce 

Steps to reproduce : 

composer.json
```json
{
    "require": {
        "phpdocumentor/reflection": "5.x-dev#cdda55ca794780f1fe119e16b9f8ff3245d4a5ac"
    }
}
```

test.php
```php
<?php
function test() {
	define('TEST', true);
}
```

demo.php
```php
<?php
include_once 'vendor/autoload.php';
$projectFactory = \phpDocumentor\Reflection\Php\ProjectFactory::createInstance();
$projectFiles = [new \phpDocumentor\Reflection\File\LocalFile('test.php')];
$project = $projectFactory->create('My Project', $projectFiles);
var_dump($project);
```

Run.
```sh
php demo.php
```

That gives:
```
Fatal error: Uncaught AssertionError: assert($file instanceof FileElement) in vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/Factory/Define.php:103
```

Hope it helps.

**Comment by jaapio** [comment]
This is fixed and will be part of the next release. 

Thank you for your nice and clear bug report.
