### ISSUE TITLE
Upgrade nikic/php-parser

### ISSUE THREAD

**Issue by theofidry** [phpDocumentor/Reflection#34]
The required version of the `nikic/php-parser` package is still `~0.9.4` on the `master` branch. Would it be possible to use a version 1.0 or superior or the develop branch will be merged to the master soon?

**Comment by mvriel** [comment]
Hello Theofidry,

I would need to check if the upgrade won't cause any BC breaks. dev-master contains version 1 of the component and develop version 2; which needs some more time to get wrapped up.

**Comment by theofidry** [comment]
Thanks for your concern @mvriel, hope there won't be any BC break!

**Comment by theofidry** [comment]
Hi @mvriel, any update regarding the possible upgrade?

**Comment by mvriel** [comment]
Hi @theofidry,

I have checked it but between 0.9.5 and 1.0.2 there have been several BC breaks in PHP-Parser; I cannot upgrade it without significant effort for which I am unable to make time atm

Sorry

**Comment by theofidry** [comment]
Ok sad :( Thanks for trying.
