### ISSUE TITLE
phpdocumentor/reflection-docblock depends on phpdocumentor/reflection-common 0.1.x, phpdocumentor/reflection depends on phpdocumentor/reflection-common 1.0.x

### ISSUE THREAD

**Issue by Ocramius** [phpDocumentor/Reflection#68]
Obvious conflict during installation:

 - phpdocumentor/reflection-docblock depends on phpdocumentor/reflection-common 0.1.x
 - phpdocumentor/reflection depends on phpdocumentor/reflection-common 1.0.x

**Comment by Ocramius** [comment]
Current workaround is to update with:

```
        "phpdocumentor/reflection-common":    "dev-master as 0.1.99"
```

**Comment by mvriel** [comment]
I have just updated all packages to use the correct composer.json settings and pushed a new build tag for the Reflection component; all should be in sync again

**Comment by mvriel** [comment]
At my machine everything is working again but can you confirm whether it works for you now?

**Comment by Ocramius** [comment]
@mvriel pulling/checking

**Comment by Ocramius** [comment]
Works! :+1:
