### ISSUE TITLE
Parameter type hint ignored

### ISSUE THREAD

**Issue by donquixote** [phpDocumentor/Reflection#81]
``` php
class C {
  function foo(MyArgInterface $x) {
  }
}
```

Here it seems that phpDocumentor does not detect the "MyArgInterface" argument type.
nikic's php-parser does correctly detect the type, but then here in \phpDocumentor\Reflection\Php\Factory\Argument::create():

```
    return new ArgumentDescriptor($object->name, $default, $object->byRef, $object->variadic);
```

This should be changed to

```
    $argDescriptor = new ArgumentDescriptor($object->name, $default, $object->byRef, $object->variadic);
    if (!empty($object->type)) {
        $argDescriptor->addType((string)$object->type);
    }
    return $argDescriptor;
```

So it adds the type.

Not sure what other consequences this would have, so I am just proposing this for discussion.

**Comment by jaapio** [comment]
In the new version 2.0.0 this will be solved. But since the whole library is rewritten this could cause issues in your project. You could have a look at the develop branch to check what needs to be changed.

Let me know if you are able to upgrade. Otherwise I will have look at this issue.

**Comment by donquixote** [comment]
It is a brand-new project (Drupal module), not yet officially published, where I want to use this.
So yes, I can upgrade :)

I am using PhpDocumentor to detect plugin annotations. Similar to what Drupal 8 does, but it also needs to detect annotations in static methods, not just in the class docblock. And it should analyze the method and/or constructor signature.

This is why the [StaticReflectionParser](https://github.com/doctrine/common/blob/master/lib/Doctrine/Common/Reflection/StaticReflectionParser.php) in Doctrine is not sufficient, and I use PhpDocumentor instead.

Btw, something really nice, which you should consider for a rewrite:
https://packagist.org/packages/vektah/parser-combinator

I am using this to parse the annotations themselves. But I guess it would be not so hard to build a grammar for the stuff you are interested in - a docblock with @param, @return etc.
You can continue to use the nikic parser for the php itself.

**Comment by jaapio** [comment]
What I meant to say is that we are ready with version 2.0.0 but is is not released yet. The develop branch contains the new code, So if you use that your issues should be fixed.

**Comment by johnbillion** [comment]
It appears that this never made it into either the 2.x or 3.x codebase. This is a feature that I'm missing from a library that I'm writing to ensure the integrity and correctness of function docblocks.

**Comment by jaapio** [comment]
You can use the version in develop, I never had time to finish it. But it should fit to your needs. We are still working on that version. But needed to fix some other high priority things first. Pleas let me know when you have any issues with that version.

**Comment by johnbillion** [comment]
Thanks for the reply. The type hint handling doesn't appear to be present in the `develop` branch either (looking at `phpDocumentor\Reflection\Php\Factory\Argument::doCreate()`.

It would be great to get this in. I'll see about opening a PR.

**Comment by jaapio** [comment]
That would be awesome! Thanks

**Comment by jaapio** [comment]
#131 fixes this issue. 
Thanks @johnbillion for detecting this issue.
