### ISSUE TITLE
Drush8 conflicts with phpDocumentor / Reflection

### ISSUE THREAD

**Issue by Sinsho** [phpDocumentor/Reflection#88]
If you installed phpDocumentor / Reflection, you're not able to install Drush8. The reason is a conflict with the nikic/php-parser Version.

phpdocumentor/phpdocumentor requires phpdocumentor/reflection (~1.0)
phpdocumentor/reflection requires <b>nikic/php-parser (~0.9.4)<b>

drush/drush requires psy/psysh (~0.6)
psy/psysh requires <b>nikic/php-parser (^1.2.1|~2.0)<b>

The newest official release of phpDocumentor / Reflection uses nikic/php-parser 1.0, which is still to old for Drush8.

It would be great if you could release a new version which uses a newer version of nikic/php-parser in order to make it run with Drush8.

**Comment by theofidry** [comment]
haha got the same issue cf. (#34, #60). It is has been upgrade for the 2.0 version but at the moment it's still an alpha ([2.0.0-alpha1](https://github.com/phpDocumentor/Reflection/releases/tag/2.0.0-alpha1)).

**Comment by Sinsho** [comment]
Thanks for the answer but the Alpha version (2-0-0-alpha1) uses the 1.0 Version. 

name     : phpdocumentor/reflection
descrip. : Reflection library to do Static Analysis for PHP Projects
keywords : phpdoc, reflection, static analysis, phpDocumentor
versions : 2.0.0-alpha1
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/phpDocumentor/Reflection.git 3516b9749cc18e4b7f7282e2dce2591a00d25365
dist     : [zip] https://api.github.com/repos/phpDocumentor/Reflection/zipball/3516b9749cc18e4b7f7282e2dce2591a00d25365 3516b9749cc18e4b7f7282e2dce2591a00d25365
names    : phpdocumentor/reflection

autoload
psr-4
phpDocumentor\ => src/phpDocumentor

requires
php >=5.4.0
psr/log ~1.0
<b>nikic/php-parser ~1.0<b>

**Comment by theofidry** [comment]
`~1.0` meets the `^1.2.1` requirement

**Comment by jaapio** [comment]
We switched recently to nikic/php-parser ^2.0 to support php7. You can use 2.0.0-alpha2 to get the latest version.
